### ISSUE TITLE
health tracking?

### ISSUE THREAD

**Issue by ofsaleem** [Hamsda/OoTRMapTracker#44]
hey, big fan of this tracker, have been using it for a while. i might be missing something but i looked through the code too and i didn't see anything about the double defense upgrade. i know its not really necessary for anything, but i like to track that stuff when possible (like the double magic).

also i noticed theres tracking logic available for hp/hc but i dont see any pieces or containers on the tracker itself.

thanks!

**Comment by Hamsda** [comment]
Yeah I have added the HP/HC items to the default items a while ago, because some people like to track them. But because health is visible on screen at basically all times, they are not included in any of the default tracking layouts. You can add them with overrides if you like though.
As for double defense, I wouldn't know what icon to use for that tbh. But as I said, I wouldn't include it in any default view anyways. If you have a suggestion for the icon though, let me know and I'll see about adding it so you only have to override one file.

**Comment by alemonplays** [comment]
I saw in a recent Stream someone using a new tracker who had this icons:
![Screenshot](https://user-images.githubusercontent.com/50206979/57086547-b4945f80-6cd4-11e9-8d1c-a7ca610dce35.png)

Taking the idea form there, I took the offical Heart Container Artwork provided by nintendo ( Information  and Artwork tooked from [here ](https://zelda.gamepedia.com/Heart_Container) ) and modified it to have a Heart Piece and Double Defense Icon as well. Fell free to use it and if you want to add them (i unfortunately wouldn't know how to do it :( ).  

[Health_Tracking_Icons.zip](https://github.com/Hamsda/OoTRMapTracker/files/3138767/Health_Tracking_Icons.zip)

I found this thread exactly because i was searching for a Health Tracking Option as well. :)
